let questionsData = [
  {
    id: 1,
    title: "Education",
    instruction: "Please describe your highest level of education.",
    status: "unanswered",
    recording: null,
    transcription: null,
  },
  {
    id: 2,
    title: "Work Experience",
    instruction: "Describe your most recent job experience.",
    status: "unanswered",
    recording: null,
    transcription: null,
  },
  {
    id: 3,
    title: "Skills",
    instruction: "Talk about your top technical and soft skills.",
    status: "unanswered",
    recording: null,
    transcription: null,
  },
  {
    id: 4,
    title: "Projects",
    instruction: "Describe a key project you have worked on.",
    status: "unanswered",
    recording: null,
    transcription: null,
  },
  {
    id: 5,
    title: "Achievements",
    instruction: "Highlight any awards or accomplishments.",
    status: "unanswered",
    recording: null,
    transcription: null,
  },
  {
    id: 6,
    title: "Hobbies",
    instruction: "Talk about your personal interests or hobbies.",
    status: "unanswered",
    recording: null,
    transcription: null,
  },
  {
    id: 7,
    title: "Languages",
    instruction: "Mention the languages you are fluent in.",
    status: "unanswered",
    recording: null,
    transcription: null,
  },
  {
    id: 8,
    title: "Certifications",
    instruction: "Describe any professional certifications you hold.",
    status: "unanswered",
    recording: null,
    transcription: null,
  },
  {
    id: 9,
    title: "Career Goals",
    instruction: "Share your short-term and long-term career goals.",
    status: "unanswered",
    recording: null,
    transcription: null,
  },
  {
    id: 10,
    title: "References",
    instruction: "Provide any references or mentors if applicable.",
    status: "unanswered",
    recording: null,
    transcription: null,
  },
];

export default questionsData;
